# Generated by Django 6.0.2 on 2026-02-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('duration', models.CharField(max_length=50)),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
