# Generated by Django 6.0.2 on 2026-05-09 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_course_code_remove_course_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_years',
        ),
    ]
