# Generated by Django 6.0.2 on 2026-05-09 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_subject_attendance_course'),
        ('courses', '0003_remove_subject_course_rename_course_name_course_name_and_more'),
        ('exams', '0002_remove_marks_subject_marks_course'),
        ('timetable', '0002_remove_timetable_end_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
