# Generated by Django 6.0.2 on 2026-05-09 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('courses', '0002_remove_course_course_code_remove_course_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
